#ifndef NPC_CONFIG_HPP_
#define NPC_CONFIG_HPP_

#define CONFIG_RT_CHECK
// #define CONFIG_MTRACE
// #define CONFIG_DTRACE
// #define CONFIG_ISA64

#define CONFIG_DEVICE
#define CONFIG_RTC_MMIO    0xa0000048
#define CONFIG_SERIAL_MMIO 0xa00003f8

#endif /* NPC_CONFIG_HPP_ */