version = 2.7.5

maxColumn = 100
align = most
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
docstrings = ScalaDoc
lineEndings = preserve
includeCurlyBraceInSelectChains = false
danglingParentheses.preset = false

docstrings.style = Asterisk
docstrings.oneline = fold

align.tokens.add = [
  {
    code = ":"
  },
  {
    code = ":="
  },
  {
    code = "="
  },
  {
    code = "->"
  },
  {
    code = "//"
  },
  {
    code = "<>"
  }
]

newlines.beforeCurlyLambdaParams = never
newlines.alwaysBeforeMultilineDef = false
newlines.implicitParamListModifierForce = [before]

verticalMultiline.atDefnSite = true

optIn.annotationNewlines = true

rewrite.rules = [SortImports, PreferCurlyFors]
